### PR TITLE
#99 Increase test coverage, add auth tests, cleanup exceptions and security

### PR DESCRIPTION
**Pull request by Mo-og**

### CODE REVIEW

**Comment by Mo-og** [comment]
|File|Coverage [58.89%]|:green_apple:|
|:-|:-:|:-:|
|[WeekService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2Finterfaces%2FWeekService.java)|100%|:green_apple:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[InvalidInputException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInputException.java)|100%|:green_apple:|
|[TemplateMessageException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FTemplateMessageException.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[JwtTokenUtil.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2Fjwt%2FJwtTokenUtil.java)|95.36%|:green_apple:|
|[InterviewerTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerTimeSlot.java)|95.14%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|92.42%|:green_apple:|
|[JwtRequestFilter.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2Fjwt%2FJwtRequestFilter.java)|90.82%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|89.2%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|89.16%|:green_apple:|
|[User.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FUser.java)|88.49%|:green_apple:|
|[CandidateTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateTimeSlot.java)|56.34%|:green_apple:|
|[BookingLimitDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingLimitDto.java)|53.27%|:green_apple:|
|[AuthController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FAuthController.java)|36.89%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|33.39%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/f99d5bbdc7dd04de082811c8efb69009a05c8a60/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|23.42%|:green_apple:|

|Total Project Coverage|63.17%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [58.57%]|:green_apple:|
|:-|:-:|:-:|
|[WeekService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2Finterfaces%2FWeekService.java)|100%|:green_apple:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[InvalidInputException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInputException.java)|100%|:green_apple:|
|[TemplateMessageException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FTemplateMessageException.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[JwtTokenUtil.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2Fjwt%2FJwtTokenUtil.java)|95.36%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|92.42%|:green_apple:|
|[JwtRequestFilter.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2Fjwt%2FJwtRequestFilter.java)|90.82%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|89.2%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|89.16%|:green_apple:|
|[User.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FUser.java)|88.49%|:green_apple:|
|[InterviewerTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerTimeSlot.java)|85.42%|:green_apple:|
|[CandidateTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateTimeSlot.java)|56.34%|:green_apple:|
|[BookingLimitDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingLimitDto.java)|53.27%|:green_apple:|
|[AuthController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FAuthController.java)|36.89%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|33.39%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/57cb5312adf7431a2921ab402f0cb5ee51064bf0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|23.42%|:green_apple:|

|Total Project Coverage|62.97%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [60.58%]|:green_apple:|
|:-|:-:|:-:|
|[WeekService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2Finterfaces%2FWeekService.java)|100%|:green_apple:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[InvalidInputException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInputException.java)|100%|:green_apple:|
|[TemplateMessageException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FTemplateMessageException.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[JwtTokenUtil.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2Fjwt%2FJwtTokenUtil.java)|95.36%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|92.42%|:green_apple:|
|[JwtRequestFilter.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2Fjwt%2FJwtRequestFilter.java)|90.82%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|89.2%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|89.16%|:green_apple:|
|[User.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FUser.java)|88.49%|:green_apple:|
|[InterviewerTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerTimeSlot.java)|85.42%|:green_apple:|
|[CandidateTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateTimeSlot.java)|56.34%|:green_apple:|
|[BookingLimitDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingLimitDto.java)|53.27%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|37.34%|:green_apple:|
|[AuthController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FAuthController.java)|36.89%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/042df775161157b354a10a112ce2833b841b82aa/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|23.42%|:green_apple:|

|Total Project Coverage|64.22%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [60.7%]|:green_apple:|
|:-|:-:|:-:|
|[WeekService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2Finterfaces%2FWeekService.java)|100%|:green_apple:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[NotFoundException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FNotFoundException.java)|100%|:green_apple:|
|[InvalidInputException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FInvalidInputException.java)|100%|:green_apple:|
|[TemplateMessageException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FTemplateMessageException.java)|100%|:green_apple:|
|[WeekServiceImp.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FWeekServiceImp.java)|100%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[JwtTokenUtil.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2Fjwt%2FJwtTokenUtil.java)|95.36%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|92.42%|:green_apple:|
|[JwtRequestFilter.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2Fjwt%2FJwtRequestFilter.java)|90.82%|:green_apple:|
|[InterviewerService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FInterviewerService.java)|89.33%|:green_apple:|
|[UserService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FUserService.java)|89.16%|:green_apple:|
|[User.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FUser.java)|88.49%|:green_apple:|
|[InterviewerSlotValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FInterviewerSlotValidator.java)|86.11%|:green_apple:|
|[InterviewerSlotDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FInterviewerSlotDto.java)|62.13%|:green_apple:|
|[InterviewerTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FInterviewerTimeSlot.java)|61.11%|:green_apple:|
|[BookingLimitDto.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2Fdto%2FBookingLimitDto.java)|53.27%|:green_apple:|
|[CandidateTimeSlot.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FCandidateTimeSlot.java)|51.87%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|37.34%|:green_apple:|
|[AuthController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FAuthController.java)|36.89%|:green_apple:|
|[Booking.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/b4aca5343615a8658545a05b51dc07d3a0185bc9/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fmodels%2FBooking.java)|23.42%|:green_apple:|

|Total Project Coverage|64.14%|:green_apple:|
|:-|:-:|:-:|

**Review by olesiayakovenko — APPROVED** [review]

**Pull request merged**
