### PR TITLE
✨️🔒️#87 Configure access to URIs according to roles

### PR DESCRIPTION
**Pull request by Mo-og**
Removed secrets from application-dev. Reworked embedded users adding. Set accesses

### CODE REVIEW

**Comment by Mo-og** [comment]
|File|Coverage [23.27%]|:green_apple:|
|:-|:-:|:-:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5ff2915ba6227ea0654affdce4388cd3f09ba520/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5ff2915ba6227ea0654affdce4388cd3f09ba520/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|85.14%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5ff2915ba6227ea0654affdce4388cd3f09ba520/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|68.82%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/5ff2915ba6227ea0654affdce4388cd3f09ba520/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|5.47%|:x:|

|Total Project Coverage|60.52%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [23.27%]|:green_apple:|
|:-|:-:|:-:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/17ddf78532fb9da92df518ff508049d2174eff3b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/17ddf78532fb9da92df518ff508049d2174eff3b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|85.14%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/17ddf78532fb9da92df518ff508049d2174eff3b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|68.82%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/17ddf78532fb9da92df518ff508049d2174eff3b/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|5.47%|:x:|

|Total Project Coverage|60.52%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [23.27%]|:green_apple:|
|:-|:-:|:-:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38a1abddd0ecec645ceb43f6dcc02b4686fcbe0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38a1abddd0ecec645ceb43f6dcc02b4686fcbe0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|85.14%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38a1abddd0ecec645ceb43f6dcc02b4686fcbe0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|68.82%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/a38a1abddd0ecec645ceb43f6dcc02b4686fcbe0/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|5.47%|:x:|

|Total Project Coverage|60.52%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [30.06%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/304b8478dfb1caab763ceaf714f61f6728b64b89/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/304b8478dfb1caab763ceaf714f61f6728b64b89/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/304b8478dfb1caab763ceaf714f61f6728b64b89/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|85.14%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/304b8478dfb1caab763ceaf714f61f6728b64b89/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|68.82%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/304b8478dfb1caab763ceaf714f61f6728b64b89/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|4.41%|:x:|

|Total Project Coverage|59.03%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [32.99%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/d325fc882bbecc41bec0c2ffc75448c802b64299/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/d325fc882bbecc41bec0c2ffc75448c802b64299/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/d325fc882bbecc41bec0c2ffc75448c802b64299/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|85.14%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/d325fc882bbecc41bec0c2ffc75448c802b64299/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|73.64%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/d325fc882bbecc41bec0c2ffc75448c802b64299/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|4.41%|:x:|

|Total Project Coverage|57.75%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [39.76%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|94.85%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|85.14%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|72.64%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|71.82%|:green_apple:|
|[PermissionValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FPermissionValidator.java)|48.28%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/eaaf6ccb9d535447b39fa4758294a06f4871ba45/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|4.41%|:x:|

|Total Project Coverage|58.14%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [40.48%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|94.85%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|85.14%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|72.64%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|71.82%|:green_apple:|
|[PermissionValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FPermissionValidator.java)|48.28%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/c15ee5fbc5141da02214705c2be6a11b45f65a85/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|6.37%|:x:|

|Total Project Coverage|58.3%|:green_apple:|
|:-|:-:|:-:|

**Comment by Mo-og** [comment]
|File|Coverage [40.48%]|:green_apple:|
|:-|:-:|:-:|
|[ApplicationErrorException.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fexceptions%2FApplicationErrorException.java)|100%|:green_apple:|
|[BookingLimitController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FBookingLimitController.java)|100%|:green_apple:|
|[WebSecurityConfig.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fsecurity%2FWebSecurityConfig.java)|100%|:green_apple:|
|[CandidateService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FCandidateService.java)|94.85%|:green_apple:|
|[InterviewPlanningApplication.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2FInterviewPlanningApplication.java)|85.14%|:green_apple:|
|[UserController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FUserController.java)|72.64%|:green_apple:|
|[SlotController.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fcontrollers%2FSlotController.java)|71.82%|:green_apple:|
|[PermissionValidator.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fvalidators%2FPermissionValidator.java)|48.28%|:green_apple:|
|[AuthService.java](https://github.com/Mo-og/intellistart-java-2022-debuggers/blob/9a053258f6c47c94fb9efc78c1172bf18c559094/src%2Fmain%2Fjava%2Fcom%2Fintellias%2Fintellistart%2Finterviewplanning%2Fservices%2FAuthService.java)|6.37%|:x:|

|Total Project Coverage|58.3%|:green_apple:|
|:-|:-:|:-:|

**Review by olesiayakovenko — APPROVED** [review]

**Pull request merged**
